# 데이터 학습

# 1) 데이터 불러오기

In [1]:
import pandas as pd

df = pd.read_csv("C:/Edu-More_AI/data/raws/mediapipe_hands.csv", header=None)
print(df.shape)
df.head()

(1200, 64)

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.705100,0.515444,-5.389623e-08,0.705374,0.502093,-0.002268,0.711818,0.489445,-0.002427,0.719494,...,0.729732,0.506300,-0.004213,0.726511,0.510217,-0.003210,0.723039,0.511973,-0.001536,pause
1,0.697020,0.490848,-6.478620e-08,0.699116,0.476119,-0.001388,0.704710,0.464746,-0.001656,0.712481,...,0.721514,0.484711,-0.001977,0.716616,0.484821,-0.000082,0.714206,0.486552,0.001871,pause
2,0.653324,0.414724,-7.009539e-08,0.647431,0.401281,-0.001151,0.646695,0.387632,-0.001355,0.650983,...,0.668632,0.388966,-0.002898,0.665011,0.393207,-0.000681,0.663907,0.396474,0.001534,pause
3,0.622652,0.396307,-6.855365e-08,0.613408,0.388752,-0.002445,0.607106,0.376377,-0.002909,0.608131,...,0.628780,0.364422,-0.004059,0.627001,0.371677,-0.002049,0.626906,0.375526,0.000285,pause
4,0.615747,0.393170,-7.238830e-08,0.605814,0.389587,-0.002808,0.598738,0.378721,-0.003495,0.598969,...,0.618435,0.364194,-0.004922,0.617452,0.371246,-0.003119,0.618033,0.375071,-0.000986,pause

In [2]:
# 열 이름 만들기

columns = []
for i in range(21):
    columns.extend([f"x{i}", f"y{i}", f"z{i}"])
columns.append("label")
df.columns = columns

df.head()

,x0,y0,z0,x1,y1,z1,x2,y2,z2,x3,...,x18,y18,z18,x19,y19,z19,x20,y20,z20,label
0,0.705100,0.515444,-5.389623e-08,0.705374,0.502093,-0.002268,0.711818,0.489445,-0.002427,0.719494,...,0.729732,0.506300,-0.004213,0.726511,0.510217,-0.003210,0.723039,0.511973,-0.001536,pause
1,0.697020,0.490848,-6.478620e-08,0.699116,0.476119,-0.001388,0.704710,0.464746,-0.001656,0.712481,...,0.721514,0.484711,-0.001977,0.716616,0.484821,-0.000082,0.714206,0.486552,0.001871,pause
2,0.653324,0.414724,-7.009539e-08,0.647431,0.401281,-0.001151,0.646695,0.387632,-0.001355,0.650983,...,0.668632,0.388966,-0.002898,0.665011,0.393207,-0.000681,0.663907,0.396474,0.001534,pause
3,0.622652,0.396307,-6.855365e-08,0.613408,0.388752,-0.002445,0.607106,0.376377,-0.002909,0.608131,...,0.628780,0.364422,-0.004059,0.627001,0.371677,-0.002049,0.626906,0.375526,0.000285,pause
4,0.615747,0.393170,-7.238830e-08,0.605814,0.389587,-0.002808,0.598738,0.378721,-0.003495,0.598969,...,0.618435,0.364194,-0.004922,0.617452,0.371246,-0.003119,0.618033,0.375071,-0.000986,pause

In [3]:
df["label"].value_counts()

label
pause     300
move      300
stop      300
select    300
Name: count, dtype: int64

In [4]:
def encoding(label):
    if label == "pause":
        return 0
    elif label == "move":
        return 1
    elif label == "stop":
        return 2
    elif label == "select":
        return 3


df["label_enc"] = df["label"].apply(lambda x: encoding(x))

In [5]:
df.head()

,x0,y0,z0,x1,y1,z1,x2,y2,z2,x3,...,y18,z18,x19,y19,z19,x20,y20,z20,label,label_enc
0,0.705100,0.515444,-5.389623e-08,0.705374,0.502093,-0.002268,0.711818,0.489445,-0.002427,0.719494,...,0.506300,-0.004213,0.726511,0.510217,-0.003210,0.723039,0.511973,-0.001536,pause,0
1,0.697020,0.490848,-6.478620e-08,0.699116,0.476119,-0.001388,0.704710,0.464746,-0.001656,0.712481,...,0.484711,-0.001977,0.716616,0.484821,-0.000082,0.714206,0.486552,0.001871,pause,0
2,0.653324,0.414724,-7.009539e-08,0.647431,0.401281,-0.001151,0.646695,0.387632,-0.001355,0.650983,...,0.388966,-0.002898,0.665011,0.393207,-0.000681,0.663907,0.396474,0.001534,pause,0
3,0.622652,0.396307,-6.855365e-08,0.613408,0.388752,-0.002445,0.607106,0.376377,-0.002909,0.608131,...,0.364422,-0.004059,0.627001,0.371677,-0.002049,0.626906,0.375526,0.000285,pause,0
4,0.615747,0.393170,-7.238830e-08,0.605814,0.389587,-0.002808,0.598738,0.378721,-0.003495,0.598969,...,0.364194,-0.004922,0.617452,0.371246,-0.003119,0.618033,0.375071,-0.000986,pause,0

# 2) 데이터 분할하기

In [6]:
from sklearn.model_selection import train_test_split

X = df.iloc[:, :-2]
y = df["label_enc"]
print(X.shape, y.shape)

(1200, 63) (1200,)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, shuffle=True
)
print(
    f"X_train: {X_train.shape}, y_train: {y_train.shape}, X_test: {X_test.shape}, y_test: {y_test.shape}"
)

X_train: (960, 63), y_train: (960,), X_test: (240, 63), y_test: (240,)

# 3) 모델 만들기

In [8]:
# 설치 필요시: uv add lightgbm
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report
import joblib

# 모델 정의 (하이퍼파라미터는 필요에 맞게 조정 가능)
model = LGBMClassifier(
    n_estimators=5, learning_rate=0.01, max_depth=-1, random_state=42
)

# 학습
model.fit(X_train, y_train)

# 예측
y_pred = model.predict(X_test)

# 평가
print(classification_report(y_test, y_pred, target_names=["pause", "move", "stop", "select"]))

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002070 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 16060
[LightGBM] [Info] Number of data points in the train set: 960, number of used features: 63
[LightGBM] [Info] Start training from score -1.394663
[LightGBM] [Info] Start training from score -1.386294
[LightGBM] [Info] Start training from score -1.386294
[LightGBM] [Info] Start training from score -1.377996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
              precision    recall  f1-score   support

       pause       1.00      0.97      0.98        62
        move       0.97      0.98      0.98        60
        stop       0.92      0.95      0.93        60
      select       0.95      0.93      0.94        58

    accuracy                           0.96       240
   macro avg       0.96      0.96      0.96       240
weighted avg       0.96      0.96      0.96       240

In [ ]:
# 모델 저장

import joblib

joblib.dump(model, "C:/Edu-More_AI/training/models/hands.pkl")

In [ ]:
import joblib

model = joblib.load("C:/Edu-More_AI/training/models/hands.pkl")